# Generated by Django 2.2.3 on 2019-07-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ideia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideia',
            name='categorias',
            field=models.CharField(choices=[('TECNOLOGICAS', 'Tecnológicas'), ('CIENTIFICA', 'Científica'), ('EDUCACAO', 'Educação'), ('PUBLICAS', 'Públicas'), ('OUTROS', 'Outros')], max_length=255, verbose_name='Categorias'),
        ),
    ]
